"""
Markdown Knowledge Base Exporter: Generates organized, beautiful, human-readable
Markdown documents in `docs/knowledge_base/universities/{CODE}/`.
"""
import os
from typing import Dict, Any
from app.utils.logger import logger
from .schemas import UniversityKnowledgePayload


class MarkdownKnowledgeExporter:
    """Exports structured university entities into clean GitHub Markdown files."""

    def __init__(self, base_output_dir: str = "../docs/knowledge_base/universities"):
        self.base_output_dir = os.path.abspath(base_output_dir)
        os.makedirs(self.base_output_dir, exist_ok=True)

    def export_university_markdown(self, payload: UniversityKnowledgePayload) -> Dict[str, str]:
        """Writes comprehensive markdown files for the given university."""
        uni_dir = os.path.join(self.base_output_dir, payload.university_code)
        os.makedirs(uni_dir, exist_ok=True)

        generated_files = {}

        # 1. Overview Markdown
        overview_path = os.path.join(uni_dir, "overview.md")
        overview_content = f"""# 🏛️ {payload.university_name} ({payload.university_code})

## 📍 Institutional Profile
- **Institution Code**: `{payload.university_code}`
- **State / Region**: Jharkhand, India
- **Knowledge Base Status**: Ingested & Verified

## 📊 Academic & Research Assets Summary
- **Academic Departments**: {len(payload.departments)}
- **Faculty & Key Researchers**: {len(payload.faculty_profiles)}
- **Centers of Excellence (CoEs)**: {len(payload.research_centers)}
- **Incubation Centers (TBIs)**: {len(payload.incubation_centers)}
- **Specialized Testing Laboratories**: {len(payload.laboratories)}

## 🧭 Societal Innovation Routing Coverage
This institution provides expertise and research capabilities across the **9 Societal Challenge Domains**:
1. Mining Safety & Engineering
2. Water Quality & Arsenic Mitigation
3. Agriculture, Soil Health & Climate Resilience
4. Healthcare, Clinical Research & Biomedical Engineering
5. Rural, Road & Urban Infrastructure
6. Clean Energy, Solar & Smart Grid Systems
7. Forestry, Ecology & Environmental Management
8. Waste Management & Circular Economy
9. Education & Digital Skill Development

---
*Auto-generated by SIH University Intelligent Pipeline.*
"""
        with open(overview_path, "w", encoding="utf-8") as f:
            f.write(overview_content)
        generated_files["overview"] = overview_path

        # 2. Departments Markdown
        dept_path = os.path.join(uni_dir, "departments.md")
        dept_content = f"""# 🎓 Academic Departments & Schools — {payload.university_name}

Total Departments Ingested: **{len(payload.departments)}**

| Department Name | Code | Head of Department | Associated Societal Domains | Source |
| :--- | :--- | :--- | :--- | :--- |
"""
        for d in payload.departments:
            domains_str = ", ".join(d.domain_tags[:3]) if d.domain_tags else "General Engineering"
            source_link = f"[Link]({d.source_url})" if d.source_url else "Official Portal"
            dept_content += f"| **{d.name}** | `{d.code or 'N/A'}` | {d.hod_name or 'N/A'} | {domains_str} | {source_link} |\n"

        dept_content += "\n\n## 📝 Department Details\n"
        for d in payload.departments:
            dept_content += f"\n### {d.name}\n"
            if d.overview:
                dept_content += f"{d.overview}\n\n"
            if d.domain_tags:
                dept_content += f"- **Domains**: `{'`, `'.join(d.domain_tags)}`\n"
            if d.source_url:
                dept_content += f"- **Official URL**: {d.source_url}\n"

        with open(dept_path, "w", encoding="utf-8") as f:
            f.write(dept_content)
        generated_files["departments"] = dept_path

        # 3. Faculty Directory Markdown
        faculty_path = os.path.join(uni_dir, "faculty_directory.md")
        fac_content = f"""# 👨‍🏫 Faculty & Research Directory — {payload.university_name}

Total Professors & Investigators: **{len(payload.faculty_profiles)}**

| Name | Designation | Department | Research Specializations | Email | Profile |
| :--- | :--- | :--- | :--- | :--- | :--- |
"""
        for fac in payload.faculty_profiles:
            interests = ", ".join(fac.research_interests[:2]) if fac.research_interests else "Research & Teaching"
            profile = f"[Profile]({fac.profile_url})" if fac.profile_url else "N/A"
            email = f"`{fac.email}`" if fac.email else "N/A"
            fac_content += f"| **{fac.name}** | {fac.designation or 'Professor'} | {fac.department_name or 'General'} | {interests} | {email} | {profile} |\n"

        with open(faculty_path, "w", encoding="utf-8") as f:
            f.write(fac_content)
        generated_files["faculty_directory"] = faculty_path

        # 4. Research Centers & CoEs
        rc_path = os.path.join(uni_dir, "research_centers.md")
        rc_content = f"""# 🔬 Centers of Excellence (CoEs) & Research Hubs — {payload.university_name}

Total Research Centers: **{len(payload.research_centers)}**

"""
        for rc in payload.research_centers:
            rc_content += f"## 🏛️ {rc.name}\n"
            if rc.thrust_areas:
                rc_content += f"- **Thrust Areas**: {', '.join(rc.thrust_areas)}\n"
            if rc.facilities_equipment:
                rc_content += f"- **Facilities & Key Setups**:\n"
                for eq in rc.facilities_equipment:
                    rc_content += f"  - {eq}\n"
            if rc.domain_tags:
                rc_content += f"- **Societal Domains**: `{'`, `'.join(rc.domain_tags)}`\n"
            if rc.source_url:
                rc_content += f"- **Source URL**: {rc.source_url}\n"
            rc_content += "\n---\n"

        with open(rc_path, "w", encoding="utf-8") as f:
            f.write(rc_content)
        generated_files["research_centers"] = rc_path

        # 5. Incubation Centers & TBIs
        tbi_path = os.path.join(uni_dir, "incubation_tbi.md")
        tbi_content = f"""# 🚀 Technology Business Incubators & Innovation Hubs — {payload.university_name}

Total Incubation Hubs: **{len(payload.incubation_centers)}**

"""
        for ic in payload.incubation_centers:
            tbi_content += f"## 🏢 {ic.name}\n"
            if ic.focus_sectors:
                tbi_content += f"- **Focus Sectors**: {', '.join(ic.focus_sectors)}\n"
            if ic.facilities_provided:
                tbi_content += f"- **Incubation Facilities & Support**:\n"
                for fac in ic.facilities_provided:
                    tbi_content += f"  - {fac}\n"
            if ic.funding_grants:
                tbi_content += f"- **Grants & Funding Programs**: {ic.funding_grants}\n"
            if ic.domain_tags:
                tbi_content += f"- **Societal Domains**: `{'`, `'.join(ic.domain_tags)}`\n"
            if ic.source_url:
                tbi_content += f"- **Official Website / Link**: {ic.source_url}\n"
            tbi_content += "\n---\n"

        with open(tbi_path, "w", encoding="utf-8") as f:
            f.write(tbi_content)
        generated_files["incubation_tbi"] = tbi_path

        # 6. Laboratories Markdown
        lab_path = os.path.join(uni_dir, "laboratories.md")
        lab_content = f"""# 🧪 Advanced Testing & Characterization Laboratories — {payload.university_name}

Total Laboratories: **{len(payload.laboratories)}**

| Laboratory Name | Department | Key Testing Capabilities & Equipment | Societal Impact Domain | Source |
| :--- | :--- | :--- | :--- | :--- |
"""
        for lab in payload.laboratories:
            equip = ", ".join(lab.key_equipment[:2]) if lab.key_equipment else "Standard Analytical Setups"
            domains_str = ", ".join(lab.domain_tags[:2]) if lab.domain_tags else "General Testing"
            source_link = f"[Link]({lab.source_url})" if lab.source_url else "N/A"
            lab_content += f"| **{lab.name}** | {lab.department_name or 'N/A'} | {equip} | {domains_str} | {source_link} |\n"

        with open(lab_path, "w", encoding="utf-8") as f:
            f.write(lab_content)
        generated_files["laboratories"] = lab_path

        logger.info(f"Generated {len(generated_files)} Markdown files in {uni_dir}")
        return generated_files
