server:
  port: ${PORT:8081}
  servlet:
    context-path: /api

spring:
  application:
    name: jharkhand-govt
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 60MB
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${DB_USER:postgres.twdhxcuxxznfqvqhtdmk}
    password: ${DB_PASSWORD:39i9?+fED6gwv!F}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 120000
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

minio:
  endpoint: ${S3_ENDPOINT:https://1e4624d96732ff52dc64930a30201276.r2.cloudflarestorage.com}
  access-key: ${S3_ACCESS_KEY:2e79907b064d41bd9068a748c4d6ab02}
  secret-key: ${S3_SECRET_KEY:236bff2b3356abec299c32a30bcc1a0b669ed748330046298560b25d5d6fd9c4}
  bucket-name: ${S3_BUCKET_NAME:public-issue}
  region: ${S3_REGION:auto}

app:
  jwt:
    secret: ${JWT_SECRET:jharkhand_innovation_portal_secure_jwt_secret_key_2026_very_long_secret}
    access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000} # 15 minutes
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7 days
  encryption:
    enabled: ${FILE_ENCRYPTION_ENABLED:true}
    secret-key: ${APP_ENCRYPTION_SECRET:JharkhandInnovationPortalAES256Key2026!} # 32-byte 256-bit AES master key


