server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: jharkhand-govt
  datasource:
    url: ${DB_URL:jdbc:postgresql://db.twdhxcuxxznfqvqhtdmk.supabase.co:5432/postgres?sslmode=require}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:39i9?+fED6gwv!F}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

